[pytest]
pythonpath = .
testpaths = tests

addopts =
    -v
    --cov=controllers
    --cov=core
    --cov=driver
    --cov=models
    --cov=ui
    --cov=utils
    --cov-report=term-missing
    --cov-report=xml